shouldRender: truef
containerPort: 80
enabled: true
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: stable

service:
  name: webapp
  type: NodePort
  port: 80
  nodePort: 30080  # puerto en el nodo, debe estar entre 30000-32767

configMap:
  PUBLIC_URL_DUMMY: "https://dummy-url.com"
webapp:
  fullname: "webapp"

tolerations:
  - key: "node-role.kubernetes.io/workload"
    operator: "Equal"
    value: "apps"
    effect: "NoSchedule"
