{{- range .Values.rbacGroups }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name }}
rules:
  {{- range .rules }}
  - apiGroups: {{ toJson .apiGroups }}
    resources: {{ toJson .resources }}
    verbs: {{ toJson .verbs }}
  {{- end }}
{{- end }}