apiVersion: v1
kind: Namespace
metadata:
  name: qdrant

---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: qdrant
  ports:
    - port: 6333
      name: http
    - port: 6334
      name: grpc


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi-premium

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: default
spec:
  serviceName: qdrant-headless
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
        tolerations:
        - key: "node-role.kubernetes.io/workload"
          operator: "Equal"
          value: "apps"
          effect: "NoSchedule"
        containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
              name: http
            - containerPort: 6334
              name: grpc
          env:
            - name: QDRANT__SERVICE__API_KEY
              value: "bnH4Ec45zsjmMtnoKjCetszWzhOadT9xLsnk8gB6omgRXI5IzbPrm4hRVZcVilvrJIW2KNKe4TNeeQhLenuqxkishFR2NS3xPavL83YnbY0nnZCQw6LIewvflPQuC8Ne"
            - name: QDRANT__STORAGE__SNAPSHOT_PATH
              value: "/qdrant/storage/full-snapshot-2025-08-11-21-10-02.snapshot"
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
        volumes:
        - name: qdrant-storage  # <- DEBE COINCIDIR CON ESTE
          persistentVolumeClaim:
            claimName: qdrant-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: qdrant
  ports:
    - port: 6333
      targetPort: 6333
      nodePort: 30633
      name: http

