trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "k8s/helm/webapp/*"

pool:
  name: Azure Pipelines

variables:
  - name: environment
    value: "dev-us"
  - name: registryConnection
    value: "Registry Dev Connection"
  - name: azureRMServiceConnection
    value: "Terraform Dev" # this is a rm to connect to ACR
  - name: repositoryName
    value: "acrregistryciokmauedev"
  - name: repositoryRG
    value: "aks-us-test-rg"
  - name: serviceName
    value: "webapp"
  - name: chartVersion
    value: "0.1.0"
  - name: imageTag
    value: $(Build.BuildNumber)
  - name: kubernetesServiceEndpoint
    value: "k8s Service Connection - Dev US"
  - name: namespace
    value: "default" # cambiando a default porque dev daba error
  - name: deployToEU
    value: true # activando variable para europa
  - name: kubernetesServiceEndpointEU
    value: "k8s Service Connection - Dev EU"

stages:
- stage: Deploy_Chart
  displayName: "Deploy Helm Chart"
  jobs:
    - job: DeployUS
      displayName: "Deploy to US"
      steps:
        - template: templates/task/helm-deploy-manifest.yaml
          parameters:
            azureRMServiceConnection: $(azureRMServiceConnection)
            registryConnection: $(registryConnection)
            namespace: $(namespace)
            kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
            chartType: "name"
            serviceName: $(serviceName)
            environment: $(environment)
            chartVersion: $(chartVersion)
            imageTag: $(imageTag)
            repositoryName: $(repositoryName)
            repositoryRG: $(repositoryRG)

    - ${{ if eq(variables['deployToEU'], true) }}:
      - job: DeployEU
        displayName: "Deploy to EU"
        steps:
          - template: templates/task/helm-deploy-manifest.yaml
            parameters:
              azureRMServiceConnection: $(azureRMServiceConnection)
              registryConnection: $(registryConnection)
              namespace: $(namespace)
              kubernetesServiceEndpoint: $(kubernetesServiceEndpointEU)
              chartType: "name"
              serviceName: $(serviceName)
              environment: $(environment)
              chartVersion: $(chartVersion)
              imageTag: $(imageTag)
              repositoryName: $(repositoryName)
              repositoryRG: $(repositoryRG)
