trigger: none
pr: none

schedules:
  - cron: "05 0 * * *" # Runs every night at midnight
    displayName: "Nightly Qdrant Volume Snapshot Pipeline"
    branches:
      include:
        - main
    always: true

pool:
  name: "Azure Pipelines" # pool name

variables:
  # Define your variables here
  environment: 'dev'
  targetResourceGroup: 'rg-qdrant-snapshot-pv' #'rg-dev'  # Target resource group variable
  azureRMServiceConnection: 'Azure Resource Manager Terraform'  # service connection for Azure

stages:
  - stage: Snapshot_Qdrant_Dev
    displayName: "Stage for dev"
    jobs:
      - job: LoginToAzure
        displayName: 'Qdrant Snapshot Job'
        steps:
          - task: AzureCLI@2
            displayName: 'Qdrant Snapshot Task'
            inputs:
              azureSubscription: $(azureRMServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Already logged into Azure with service connection."
                chmod +x ./scripts/aci_temporary_runner.sh
                ./scripts/aci_temporary_runner.sh $(environment) $(targetResourceGroup)
