trigger: none
pr: none

schedules:
  - cron: "05 0 * * *" # Runs every night at midnight
    displayName: "Nightly Qdrant Volume Snapshot Pipeline"
    branches:
      include:
        - main
    always: true

pool:
  name: "ubuntu-latest" # pool name

variables:
  # Define your variables here
  environment: 'dev'
  resourceGroup: 'rg-dev'
  targetResourceGroup: 'rg-qdrant-snapshot'  # Target resource group variable
  azureRMServiceConnection: 'Azure Resource Manager Terraform'  # service connection for Azure

stages:
  - stage: Snapshot_Qdrant_Dev
    displayName: "Stage for dev"
    jobs:
      - job: LoginToAzure
        displayName: 'Login To Azure'
        steps:
          - task: AzureCLI@2
            displayName: 'Login to Azure'
            inputs:
              azureSubscription: $(azureRMServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Logging into Azure..."
                az account set --subscription $(azureRMServiceConnection)

      - job: Snapshot_Qdrant
        displayName: "Run qdrant_volume_snapshot.sh for dev"
        timeoutInMinutes: 15
        steps:
          - task: Bash@3
            displayName: "Run qdrant_volume_snapshot.sh for dev"
            inputs:
              targetType: 'inline'
              script: |
                chmod +x ./scripts/qdrant_volume_snapshot.sh
                ./scripts/qdrant_volume_snapshot.sh $(environment) $(targetResourceGroup)
